### ISSUE TITLE
panicked at 'overflow when subtracting durations'

### ISSUE THREAD

**Issue by Homer-Sim** [hatzel/vorleser-server#31]
Hello,
I tried this:
docker run -it -d\
  --name=vorleser \
  -p 8077:8000 \
  -v /docker/config/vorleser:/var/lib/vorleser \
  -v /media/daten/MEDIEN/Kinderhörbücher:/audiobooks:ro \
  --restart unless-stopped \
  vorleser/server

and thean did your recommanded commands within container (respose said succesfull)

but I am receiving this error:

`22:27:09 [INFO] POST /api/update_playstates application/json (update_playstates)

22:27:09 [INFO] GET /api/coverart/<book_id> (get_coverart)

22:27:09 [INFO] GET /api/audiobooks/<book_id> (get_audiobook)

22:27:09 [INFO] GET /api/audiobooks (get_audiobooks)

22:27:09 [INFO] 🛰  Mounting '/api/auth':

22:27:09 [INFO] POST /api/auth/login application/json (login)

22:27:09 [INFO] POST /api/auth/logout (logout)

22:27:09 [INFO] POST /api/auth/logout_all (logout_all)

22:27:09 [INFO] POST /api/auth/register application/json (register)

22:27:09 [INFO] GET /api/auth/whoami (whoami)

22:27:09 [INFO] 👾  Catchers:

22:27:09 [INFO] 400

22:27:09 [INFO] 401

22:27:09 [INFO] 403

22:27:09 [INFO] 404

22:27:09 [INFO] 500

22:27:09 [INFO] 503

22:27:09 [INFO] 📡  Fairings:

22:27:09 [INFO] 1 response: Add CORS headers to requests

22:27:09 [INFO] 🚀  Rocket has launched from http://0.0.0.0:8000

22:27:13 [INFO] GET / text/html:

22:27:13 [ERROR] No matching routes for GET / text/html.

22:27:13 [WARN] Responding with 404 Not Found catcher.

22:27:13 [INFO] Response succeeded.

22:27:19 [INFO] Completed scan, result is: Ok(())

22:31:42 [INFO] GET / text/html:

22:31:42 [ERROR] No matching routes for GET / text/html.

22:31:42 [WARN] Responding with 404 Not Found catcher.

22:31:42 [INFO] Response succeeded.

22:36:05 [INFO] GET / text/html:

22:36:05 [ERROR] No matching routes for GET / text/html.

22:36:05 [WARN] Responding with 404 Not Found catcher.

22:36:05 [INFO] Response succeeded.

22:36:49 [INFO] GET / text/html:

22:36:49 [ERROR] No matching routes for GET / text/html.

22:36:49 [WARN] Responding with 404 Not Found catcher.

22:36:49 [INFO] Response succeeded.

22:37:19 [INFO] Scanning library: /audiobooks/

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/01 - Track  1.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/02 - Track  2.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/03 - Track  3.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/04 - Track  4.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/05 - Track  5.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/06 - Track  6.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/07 - Track  7.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/08 - Track  8.mp3"))

22:37:19 [INFO] Scanning multi-file audiobook at "/audiobooks/Der Geist des Apothekers"

[mp3 @ 0x7fc3b7c5c600] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5cc00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5cc00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5d200] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5d800] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5de00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5e400] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5ea00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5f000] Estimating duration from bitrate, this may be inaccurate

22:37:19 [INFO] writing header

22:37:19 [INFO] wrote header

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 81 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 84 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 80 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5f600] Audio packet of size 84 (starting with 00000000...) is invalid, writing it anyway.

22:37:19 [INFO] writing trailer

thread '<unnamed>' panicked at 'overflow when subtracting durations', libcore/option.rs:1010:5

note: Run with `RUST_BACKTRACE=1` for a backtrace.

22:37:19 [INFO] Completed scan, result is: Err(Any)

22:47:19 [INFO] Scanning library: /audiobooks/

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/01 - Track  1.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/02 - Track  2.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/03 - Track  3.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/04 - Track  4.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/05 - Track  5.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/06 - Track  6.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/07 - Track  7.mp3"))

entry Ok(DirEntry("/audiobooks/Der Geist des Apothekers/08 - Track  8.mp3"))

22:47:19 [INFO] Scanning multi-file audiobook at "/audiobooks/Der Geist des Apothekers"

[mp3 @ 0x7fc3b7c5f000] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5ea00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5ea00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5e400] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5de00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5d800] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5d200] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5cc00] Estimating duration from bitrate, this may be inaccurate

[mp3 @ 0x7fc3b7c5c600] Estimating duration from bitrate, this may be inaccurate

22:47:19 [INFO] writing header

22:47:19 [INFO] wrote header

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 81 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 84 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 82 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 80 (starting with 00000000...) is invalid, writing it anyway.

[mp3 @ 0x7fc3b7c5fc00] Audio packet of size 84 (starting with 00000000...) is invalid, writing it anyway.

22:47:20 [INFO] writing trailer

thread '<unnamed>' panicked at 'overflow when subtracting durations', libcore/option.rs:1010:5

22:47:20 [INFO] Completed scan, result is: Err(Any)
`

**Comment by ahti** [comment]
Possibly caused by https://github.com/getsentry/sentry-rust/pull/300, i'll see about updating the sentry dependency soon.

**Comment by ahti** [comment]
Hm, actually I suspect [this line](https://github.com/vorleser/vorleser-server/blob/eae2bffab8cc406372fd73620f3fec5fb79459c4/src/helpers/mllt.rs#L131) might be the culprit.

Would it be possible for you to provide me with access to the Geist des Apothekers audiobook files, so I can try to debug this on my machine @Homer-Sim? My email should be visible on my GitHub profile.

**Comment by Homer-Sim** [comment]
Sorry for late reply,
how should I send you the files? Is here a privat message option on Github?

**Comment by ahti** [comment]
If you could send me a quick email (ahti333@gmail.com) I can send you a link where you can upload the files :)
